# Generated by Django 4.2.5 on 2023-10-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Difficulty_level",
                    models.CharField(
                        choices=[("H", "HARD"), ("M", "MEDIUM"), ("S", "SIMPLE")],
                        max_length=1,
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.questions",
                    ),
                ),
            ],
        ),
    ]
